### ISSUE TITLE
PHP Fatal error: Uncaught Error: Cannot access empty property

### ISSUE THREAD

**Issue by philgruneich** [getkirby/toolkit#190]
````
2016/09/11 22:29:39 [error] 1601#1601: *4433 FastCGI sent in stderr: 'PHP message: PHP Fatal error: Uncaught Error: Cannot access empty property in /var/www/example.com/html/kirby/toolkit/lib/obj.php:18

Stack trace:
#0 /var/www/example.com/html/kirby/kirby/request.php(22): Obj->__construct(Array)
#1 /var/www/example.com/html/kirby/kirby.php(568): KirbyRequest->params()
#2 /var/www/example.com/html/kirby/kirby/component/response.php(29): Kirby->render(Object(Page))
#3 /var/www/example.com/html/kirby/kirby.php(686): KirbyComponentResponse->make(Object(Page))
#4 /var/www/example.com/html/index.php(17): Kirby->launch()
#5 {main}
thrown in /var/www/example.com/html/kirby/toolkit/lib/obj.php on line 18' while reading response header from upstream, client: 111.111.111.11, server: example.com, request: 'GET /blog/:9 HTTP/1.1', upstream: 'fastcgi://unix:/var/run/php/php7.0-fpm.sock:', host: 'example.com'
````

Error occurs whenever you access a Kirby page with, for example, `/:anything`, for example, `https://getkirby.com/:anything` doesn't throw a 404, but a blank page and probably logs that error.

**Comment by lukasbestle** [comment]
Thank you, this is now fixed directly in the `Obj` class.
